import assert from 'node:assert/strict';
import {createAimLock,stepAimLock} from '../src/sim/aim-lock.ts';
import {createAimView,aimAngleDelta,aimCamera} from '../src/sim/aim-view.ts';
import {NO_INPUT} from '../src/sim/player.ts';
import {fireBeam} from '../src/sim/laser.ts';
const aim={...createAimView(),active:true,yaw:4090};
const lock=createAimLock(),eye={x:0,y:0,z:0};
const targets=[{id:4,x:5000,y:-1000,z:10000},{id:7,x:-5000,y:500,z:10000}];
const tick=(input={},list=targets)=>stepAimLock(lock,aim,eye,{...NO_INPUT,...input},list);
tick({cameraRight:true});assert.equal(lock.target,4);assert(lock.locked);
for(let i=0;i<40;i++)tick({cameraRight:true});
assert.equal(lock.target,4,'held cycle never repeats');
assert(aim.yaw<1024,'wraparound takes short path');assert(aim.pitch>0,'tracks height');
tick();tick({cameraRight:true});assert.equal(lock.target,7);
tick();tick({cameraRight:true});assert.equal(lock.target,4,'forward wraps');
tick();tick({cameraLeft:true});assert.equal(lock.target,7,'reverse wraps');
tick({moveX:1});assert(!lock.locked,'manual aim breaks tracking');
const manualYaw=aim.yaw;tick();assert.equal(aim.yaw,manualYaw,'released lock does not pull aim');
tick({cameraRight:true});assert.equal(lock.target,7,'re-lock same selection');assert(lock.locked);
tick({},[targets[0]!]);assert(!lock.locked);assert.equal(lock.target,null,'removed target releases lock');
tick({cameraRight:true},[{id:9,x:0,y:0,z:0x20000}]);assert(!lock.locked,'exclusive retail range');
tick();tick({cameraRight:true});
for(let i=0;i<80;i++)tick({},[{...targets[0]!,x:7000}]);
assert(Math.abs(aimAngleDelta(aim.yaw,Math.round(Math.atan2(7000,10000)*2048/Math.PI)))<=3,'moving target follows');
const camera=aimCamera(aim,{x:0,y:0x3000,z:0});
const blocked=fireBeam([],camera.eye,aim.yaw,0,[],()=>0.25,aim.pitch);
assert(blocked.wall,'lock does not bypass walls');
assert(Math.abs(Math.hypot(blocked.beam.to.x,blocked.beam.to.y,blocked.beam.to.z)-0x8000)<10);
aim.active=false;tick();assert(!lock.locked);assert.equal(lock.target,null);
console.log('PASS: acquire, held edges, forward/reverse wrap, manual break, re-lock, moving/lost/range targets, wall collision and exit reset.');
