import {readEffectTable} from '../src/formats/effect-table.ts';
import {createEffects,spawnEffect,stepEffects,type EffectWorld} from '../src/sim/effects.ts';
import {RandomStream} from '../src/sim/creatures.ts';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {readLensFlareTable,buildLensFlares,flareRay,levelFlareSources} from '../src/sim/lens-flare.ts';
import {readSpriteTable} from '../src/formats/sprite-table.ts';
import {createOptions,stepOptions} from '../src/front/options.ts';
import {DEFAULT_KEYS} from '../src/sim/input.ts';
const exe=readFileSync(`${process.argv[2]??'Toy Story 2'}/toy2.exe`);
const table=readLensFlareTable(exe),sprites=readSpriteTable(exe,3);
assert.equal(table.length,17);assert.equal(table.filter(t=>t.sprite).length,10);
for(const entry of table)if(entry.sprite)assert(sprites[entry.sprite]?.frames[0]);
assert.throws(()=>readLensFlareTable(new Uint8Array(2)));
const source=levelFlareSources(3)[0]!;assert.equal(levelFlareSources(1).length,0);
const project=()=>({x:256,y:128,depth:0.5});
const clear=()=>false;
const centre=buildLensFlares([source],table,project,clear);assert.equal(centre.length,10);
assert.equal(centre[0]!.colour[0],97);assert.equal(centre[0]!.x,219);assert.equal(centre[0]!.y,104);
assert.equal(buildLensFlares([source],table,project,()=>true).length,0);
for(const p of [{x:513,y:128,depth:.5},{x:256,y:-1,depth:.5},{x:256,y:128,depth:0},{x:256,y:128,depth:1},{x:256,y:128,depth:.001},{x:NaN,y:128,depth:.5}])assert.equal(buildLensFlares([source],table,()=>p,clear).length,0);
const many=Array.from({length:12},()=>source);assert.equal(buildLensFlares(many,table,project,clear).length,80);
let n=0;assert.equal(buildLensFlares(many,table,project,()=>++n<=4).length,80,'blocked lights do not consume visible slots');
assert.deepEqual(flareRay({x:10,y:20,z:30},{...source,x:-1,y:31,z:31}),{x:-9,y:9,z:0});
const off=buildLensFlares([source],table,()=>({x:192,y:128,depth:.5}),clear);
assert(off[1]!.x>off[0]!.x,'disabled rows still advance toward centre');
const s=createOptions({sfx:8,bgm:8,activeCamera:true,detail:1,keys:DEFAULT_KEYS});s.page=3;
const tick=(now=0)=>stepOptions(s,{now,was:0},()=> '');
tick(32);assert.equal(s.value.lensFlare,false);tick();tick(0x1000);assert.equal(s.value.lensFlare,true);
console.log('PASS: local 17-row flare table/art, fixed source, clipping, occlusion, visible-source cap, chain spacing, ray truncation and option rollback.');

const effectsTable=readEffectTable(exe),sim=createEffects(effectsTable.kinds,effectsTable.modes,new RandomStream(new Uint8Array([0])));
const kind=effectsTable.kinds.find(t=>t?.mode===7)!.kind;
const world:EffectWorld={cameraX:0,cameraY:0,cameraZ:0,playerX:0,playerY:0,playerZ:0,playerYaw:0,playerVx:0,playerVz:0,groundAt:()=>null,waterY:null};
for(let i=0;i<12;i++)assert(spawnEffect(sim,world,0,0,0,0,0,0,0,0,0,kind));
stepEffects(sim,world);assert.equal(sim.lights.filter(l=>l.glow).length,12,'visibility cap is deferred to the renderer');
const coloured=createEffects(effectsTable.kinds,effectsTable.modes,new RandomStream(new Uint8Array([0])));
const effect=spawnEffect(coloured,world,0,0,0,0,0,0,0,0,0,kind)!;
effect.mode=0x1a;effect.r=16;effect.g=32;effect.b=48;effect.life=4;
stepEffects(coloured,world);assert(coloured.lights.some(l=>l.glow&&l.r===32&&l.g===32&&l.b===48));
console.log('PASS: effect glow emission, deferred visibility cap and mode 0x1a colour channels.');
