/** Retail menu timing and safe rebinding checks, using only the local install. */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createOptions, stepOptions, configureOptionKey, configureOptionButton, CONTROL_ACTIONS } from '../src/front/options.ts';
import { createLoadScreen, enterSaveSlots, stepLoadScreen } from '../src/front/load-screen.ts';
import { DEFAULT_KEYS, DEFAULT_PAD, InputSource, validBindingCode } from '../src/sim/input.ts';
import { exeString } from '../src/sim/level-data.ts';
import { readSpriteTable } from '../src/formats/sprite-table.ts';
import { freshBlock, encodeSaveFile } from '../src/formats/save-file.ts';
import { importProgress } from '../src/loader/save.ts';
const exe=readFileSync(`${process.argv[2]??'Toy Story 2'}/toy2.exe`);
const text=(a:number)=>exeString(exe,a<0?exe.readUInt32LE(-a-0x400000):a);
const sprites=readSpriteTable(exe,0);
for(const code of ['KeyZ','Numpad1','F5','BracketLeft'])assert(validBindingCode(code));
for(const code of ['Enter','ControlLeft','Tab','MadeUpKey'])assert(!validBindingCode(code));
const s=createOptions({sfx:8,bgm:6,activeCamera:true,detail:1,keys:DEFAULT_KEYS});
s.page=0;
const tick=(now=0,was=0)=>{
 const r=stepOptions(s,{now,was},text);
 for(const i of r.frame.items)if(i.kind==='sprite')assert(sprites[i.index]?.frames[i.frame],`valid sprite ${i.index}/${i.frame}`);
 return r;
};
const advance=(n:number)=>{for(let i=0;i<n;i++)tick();};
configureOptionKey(s,'Space');assert(s.capture);configureOptionKey(s,'KeyZ');assert(s.capture,'capture waits for opening key release');
advance(30);configureOptionKey(s,'KeyZ');assert.equal(s.value.keys.up[0],'KeyZ');
advance(30);configureOptionKey(s,'Space');configureOptionKey(s,'Escape');assert(!s.capture);assert.equal(s.page,0);
advance(30);tick(0x4000);assert(s.capture);tick(0x1000);assert.equal(s.page,0,'pad Cancel only closes capture');
for(let i=0;i<8;i++)configureOptionKey(s,'ArrowDown');tick();assert.equal(s.subrow,8);assert.equal(s.controlTop,4);
const ys=new Set(tick().frame.items.flatMap(i=>i.kind==='sprite'&&i.y>=80&&i.y<=144?[i.y]:[]));
assert.deepEqual([...ys],[80,96,112,128,144]);
s.subrow=CONTROL_ACTIONS.indexOf('jump');advance(30);configureOptionKey(s,'Space');advance(30);
configureOptionButton(s,1);assert.equal(s.value.pad.jump[0],1);assert.equal(s.value.pad.fire[0],0,'duplicate button swaps');
assert.deepEqual(DEFAULT_PAD.jump,[0],'default bindings remain immutable');
configureOptionKey(s,'Enter');assert.equal(s.page,-1);
s.page=0;s.captureLock=0;s.snapshot=structuredClone(s.value);s.value.pad.jump=[7];tick(0x1000);assert.deepEqual(s.value.pad.jump,[1],'Cancel rolls back pad too');
// Bound buttons actually drive the controller, not only menu labels.
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{getGamepads:()=>[{connected:true,axes:[0,0],buttons:Array.from({length:16},(_,i)=>({pressed:i===1}))}]}});
const input=new InputSource(DEFAULT_KEYS,s.value.pad);assert(input.read().jump);assert(!input.read().fire);
s.page=3;s.subrow=0;s.value.detail=0;s.gfxRepeat=0;
tick(32);assert.equal(s.value.detail,1);for(let i=0;i<15;i++)tick(32,32);assert.equal(s.value.detail,1);tick(32,32);assert.equal(s.value.detail,2);
assert(!tick().frame.items.some(i=>i.kind==='sprite'&&i.index===56&&i.frame===2),'no right arrow at high detail');
s.snapshot=structuredClone(s.value);s.gfxRepeat=0;tick(64);tick();tick(64);tick();tick(32);assert.equal(s.value.animatedTextures,false);tick();tick(0x1000);assert.equal(s.value.animatedTextures,true,'Cancel rolls back animated textures');
const progress=importProgress(encodeSaveFile('',freshBlock()));
const slots=Array.from({length:8},(_,i)=>({name:`slot ${i+1}`,progress:i===0?progress:null}));
const load=createLoadScreen(slots);
const lt=(now=0,was=0)=>stepLoadScreen(load,{now,was},text);
for(let i=0;i<30;i++)lt(0x4000);assert.equal(load.page,'root','entry lock lasts 30 ticks');
lt(0x4000);assert.equal(load.page,'load');assert.equal(load.lock,29);
assert.equal(lt(0x4000).done,null);lt(64);assert.equal(load.row,1,'slot navigation works during lock');
for(let i=0;i<30;i++)lt();assert.equal(lt(0x4000).done,null);assert.equal(load.pending,null,'empty slot cannot load');
lt(16);assert.equal(load.row,0);lt();lt(0x4000);assert.equal(load.pending,'load:0');
for(let i=0;i<42;i++){const r=lt();assert.equal(r.done,null);assert.equal(r.frame.items.length,0,'only backdrop during fade');}
assert.equal(lt().done,'load:0');
const save=createLoadScreen(slots);save.lock=0;save.row=1;
stepLoadScreen(save,{now:0x4000,was:0},text);assert.equal(save.page,'save');
for(let i=0;i<30;i++)stepLoadScreen(save,{now:0,was:0},text);
stepLoadScreen(save,{now:0x1000,was:0},text);assert.equal(save.row,1,'back preserves root selection');assert.equal(save.lock,29);
enterSaveSlots(save,'save',7);save.lock=0;stepLoadScreen(save,{now:0x4000,was:0},text);
assert.equal(save.pending,'save:7');
console.log('PASS: five-row controller scrolling, capture gates/cancel, keyboard and pad rebinding, actual bound input, graphics repeat/arrows, load/save locks, empty slots and exit fade.');
