import assert from 'node:assert/strict';
import {createPointLights,addPointLight,stepPointLights} from '../src/sim/point-light.ts';
import {lightPlayerColours} from '../src/render/player-light.ts';
const player={x:0,y:8192,z:0},orange={x:0,y:0,z:256,r:240,g:128,b:0,life:32,owner:1};
let pool=createPointLights();addPointLight(pool,orange);
assert.equal(pool.slots.length,4);
let lit=stepPointLights(pool,player)!;
assert.deepEqual(lit.direction,{x:0,y:0,z:1});assert.deepEqual(lit.colour,[239,127,0]);
assert.equal(pool.slots[0]!.life,31);
for(let i=0;i<30;i++)assert(stepPointLights(pool,player));
assert(stepPointLights(pool,player),'expiry starts a return blend');
assert.equal(pool.remaining,63);
for(let i=0;i<64;i++)stepPointLights(pool,player);
assert.equal(stepPointLights(pool,player),null);
pool=createPointLights();
for(let i=0;i<4;i++)addPointLight(pool,{...orange,x:i,life:20+i});
addPointLight(pool,{...orange,x:99});assert.equal(pool.slots[0]!.x,99);
pool=createPointLights();addPointLight(pool,{...orange,x:128*256,z:128*256});
assert(stepPointLights(pool,player),'inclusive squared 0x8000 cutoff');
pool=createPointLights();addPointLight(pool,{...orange,x:129*256,z:128*256});
assert.equal(stepPointLights(pool,player),null);assert.equal(pool.slots[0]!.life,0);
pool=createPointLights();addPointLight(pool,{...orange,z:512});addPointLight(pool,{...orange,z:256,r:40});
assert.equal(stepPointLights(pool,player)!.colour[0],39,'nearest live source');
pool=createPointLights();addPointLight(pool,orange);addPointLight(pool,{...orange,r:40});
assert.equal(stepPointLights(pool,player)!.colour[0],239,'first slot wins equal distance');
const positions=new Float32Array([0,0,0,1,0,0,0,1,0]),base=new Float32Array(9).fill(0.1);
const front=lightPlayerColours(positions,base,[0,0,1],[240,128,0]);
assert(front[0]!>front[1]!&&front[1]!>front[2]!);assert.equal(front[2],base[2]);
assert.deepEqual(lightPlayerColours(positions,base,[0,0,-1],[240,128,0]),base);
assert.deepEqual(lightPlayerColours(positions,base,[0,0,0],[240,128,0]),base);
assert.deepEqual(lightPlayerColours(new Float32Array(9),base,[0,0,1],[240,128,0]),base);
assert.equal(base[0],Math.fround(0.1),'unlit colours remain reusable');
console.log('PASS: four slots, replacement, lifetime, nearest/ties, range cutoff, attenuation and directional colour reset.');

pool=createPointLights();
addPointLight(pool,{...orange,z:16384,life:2});
const initial=stepPointLights(pool,player)!;
assert.deepEqual(initial.colour,[225,120,0]);
assert.equal(pool.remaining,0,'temporary owner takes effect immediately');
assert.deepEqual(stepPointLights(pool,player),initial,'first return tick keeps outgoing sample');
assert.equal(pool.remaining,63);
for(let i=0;i<32;i++)lit=stepPointLights(pool,player)!;
assert.deepEqual(lit.direction,{x:0,y:0,z:32});
assert.deepEqual(lit.colour,[118,63,0],'blend position/RGB before distance attenuation');
assert.equal(pool.remaining,31);
addPointLight(pool,{...orange,z:-257,r:80,g:0,owner:2});
lit=stepPointLights(pool,player)!;
assert.equal(pool.remaining,0,'new temporary owner interrupts return immediately');
assert.deepEqual(lit.direction,{x:0,y:0,z:-2});
assert.deepEqual(lit.colour,[79,0,0]);
assert.equal(pool.from.z,7936,'interrupted blend captures the current interpolated position');
assert.equal(pool.from.r,116,'interrupted colour division truncates toward zero');

pool=createPointLights();
addPointLight(pool,{...orange,z:512,life:4});stepPointLights(pool,player);
addPointLight(pool,{...orange,z:256,r:80,life:20});
assert.equal(stepPointLights(pool,player)!.direction.z,2,'same owner retains previous slot');
assert.equal(pool.selected,0);
stepPointLights(pool,player);stepPointLights(pool,player);
assert.equal(pool.slots[0]!.life,0);
assert.equal(pool.selected,0,'same-owner retention also applies after old slot expires');
for(const slot of pool.slots)slot.life=0;
stepPointLights(pool,player);assert.equal(pool.remaining,63);
for(let i=0;i<64;i++)stepPointLights(pool,player);
assert.equal(pool.remaining,0);assert.equal(stepPointLights(pool,player),null);
assert.equal(createPointLights().remaining,0,'fresh state has no retained fade');
console.log('PASS: immediate temporary selection, 64-tick return, position/RGB interpolation, interruption and same-owner slot retention.');
