/** Original 0042d47f..0042d57d attack boundaries; installed placement and effects. */
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {unpackRaw} from '../src/formats/rnc.ts';
import {parseCreatureList} from '../src/formats/creatures.ts';
import {createCreatureSim, CREATURE_FLAGS, RandomStream, stepSmithAttack} from '../src/sim/creatures.ts';
import {ANIM_SCRIPTS} from '../src/sim/creature-data.ts';
import {readEffectTable,EFFECT_FLAGS,EFFECT} from '../src/formats/effect-table.ts';
import {createEffects,spawnEffect,stepEffects,touchPlayer} from '../src/sim/effects.ts';
const raw=unpackRaw(readFileSync('Toy Story 2/data/level04/level1.raw'));
const p=parseCreatureList(raw.find(r=>r.type===0x23)!.data).find(c=>c.slot===46)!;
const fresh=()=>createCreatureSim([p],{groundY:()=>null},new RandomStream(new Uint8Array([0])),14);
const sim=fresh(),c=sim.creatures[0]!;
const player={x:c.x+200*256,y:c.y,z:c.z};
c.animState=1;
const tick=(dt=1,chasing=true)=>stepSmithAttack(sim,c,player,chasing,dt);
tick();assert.equal(c.animState,1,'strict distance cutoff');
player.x=c.x;tick(1,false);assert.equal(c.animState,1,'must be chasing');
player.y=c.y+200*256;tick();assert.equal(c.animState,1,'distance includes height');
player.y=c.y;tick();assert.equal(c.animState,3);assert.equal(c.record.speed,0);
assert.equal(c.animScript,ANIM_SCRIPTS[24]);assert.equal(c.timer,62);
assert.equal(sim.smithThrows.length,0);
tick(61);assert.equal(c.timer,1);assert.equal(sim.smithThrows.length,0);
tick();assert.deepEqual(sim.smithThrows,[c]);assert.equal(sim.sounds[0]!.event,0xa7);
tick();assert.equal(sim.smithThrows.length,1,'one release per attack');
c.frame=46<<16;c.pc=27;tick();assert.equal(c.pc,27,'frame 46 still throws');
c.flags|=CREATURE_FLAGS.scriptVelocity|CREATURE_FLAGS.chase;
c.frame=47<<16;tick();assert.equal(c.pc,16);assert.equal(c.wait,0);assert.equal(c.record.speed,16);
assert.equal(c.flags&(CREATURE_FLAGS.scriptVelocity|CREATURE_FLAGS.chase),0);
c.animState=1;tick();assert.equal(c.timer,62,'next approach can attack again');
c.health=9;tick(63);assert.equal(c.timer,0);assert.equal(sim.smithThrows.length,1,'defeat cancels pending release');
const reset=fresh();assert.equal(reset.creatures[0]!.timer,0);assert.equal(reset.smithThrows.length,0);
reset.level=15;reset.creatures[0]!.animState=1;
stepSmithAttack(reset,reset.creatures[0]!,reset.creatures[0]!,true);
assert.equal(reset.creatures[0]!.animState,1,'finale isolated');
const table=readEffectTable(readFileSync('Toy Story 2/toy2.exe'));
const effects=createEffects(table.kinds,table.modes,sim.rand);
const world={cameraX:0,cameraY:0,cameraZ:0,playerX:20000,playerY:0,playerZ:30000,
 playerYaw:0,playerVx:0,playerVz:0,groundAt:()=>null,waterY:null};
const axe=spawnEffect(effects,world,0,-5000,0,0,-2,0,1024*4,0,0,0x66)!;
assert(axe);axe.pitch=-1;assert(axe.flags&EFFECT_FLAGS.homing);assert(axe.flags&EFFECT_FLAGS.hurts);
assert.equal(axe.gravity,1024);const y=axe.y;
stepEffects(effects,world);assert.equal(axe.y,y,'pitch -1 keeps the axe horizontal');
assert(axe.x!==0||axe.z!==0,'installed axe template actually moves');
world.playerX=axe.x;world.playerY=axe.y+EFFECT.hitAbove;world.playerZ=axe.z;
touchPlayer(effects,world);assert.notEqual(effects.hurt,null,'axe contact hurts Buzz');
console.log('PASS: Smith range/chase gates, animation and exact release clock, movement handoff, repeat/cancel/reset/finale isolation, installed homing projectile horizontal flight and contact damage.');
