import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createTarmacWeather,stepRain,stepTarmacWeather,type WeatherWorld} from '../src/sim/tarmac-weather.ts';
import {readEffectTable} from '../src/formats/effect-table.ts';
import {createEffects,spawnChild,liveEffects,stepEffects,type EffectWorld} from '../src/sim/effects.ts';
import {RandomStream} from '../src/sim/creatures.ts';
const splash:{x:number;y:number;z:number}[]=[];
let reads=0;
const w:WeatherWorld={render:{x:100,y:-10000,z:200,yaw:0,pitch:0},follow:{x:100,y:-10000,z:200,yaw:0},
  playerVY:0,zone:0,eighthTick:false,fading:false,byte:()=>{reads++;return 128;},ground:()=>0,splash:at=>splash.push(at)};
let s=createTarmacWeather();
stepRain(s,w);assert.equal(reads,4);
assert.deepEqual(s.rain[7],{x:100,y:-91920,z:82120,bottom:-1});
stepRain(s,w);assert.equal(s.rain[7]!.y,-87824);assert.equal(s.rain.filter(d=>d.bottom!==0).length,2);
s=createTarmacWeather();w.zone=3;stepRain(s,w);assert.equal(s.rain[7]!.bottom,55536,'travel range clips authored zone-3 floor');
w.playerVY=2000;stepRain(s,w);assert.equal(s.rain[7]!.y,-83824,'fast downward camera-follow compensation');
w.playerVY=0;w.zone=0;
s=createTarmacWeather();for(const d of s.rain)Object.assign(d,{bottom:10000,y:0});
stepRain(s,w);assert.equal(s.quota,256,'full pool retains quota');
stepRain(s,w);stepRain(s,w);assert(s.rain.every(d=>d.bottom===0),'past floor retires drops');
stepRain(s,w);assert.equal(s.rain.filter(d=>d.bottom!==0).length,4,'quota refills using available slots');
s=createTarmacWeather();w.eighthTick=true;stepTarmacWeather(s,w);
assert.deepEqual(splash,[{x:100,y:0,z:49352}]);assert(s.thunder,'initial zero-delay register fires once');
w.ground=()=>null;stepTarmacWeather(s,w);assert.equal(splash.length,1,'no floor no splash');
w.ground=()=>-20000;stepTarmacWeather(s,w);assert.equal(splash.length,1,'roof above camera rejects splash');
w.ground=()=>0;w.eighthTick=false;
s=createTarmacWeather();s.thunderDelay=20000;
for(let i=0;i<168;i++)stepTarmacWeather(s,w);
assert.equal(s.flash,32);assert.equal(s.brightness,128);
stepTarmacWeather(s,w);assert.equal(s.flash,31);assert.equal(s.brightness,221);
assert.equal(s.thunderDelay,127);assert.deepEqual(s.thunderAt,{x:100,y:-10000,z:65736});
for(let i=0;i<31;i++)stepTarmacWeather(s,w);
assert.equal(s.flash,0);assert.equal(s.brightness,128);
stepTarmacWeather(s,w);assert.equal(s.flash,288,'random cooldown');
for(let i=0;i<94;i++)stepTarmacWeather(s,w);assert(!s.thunder);
stepTarmacWeather(s,w);assert(s.thunder);assert.equal(s.thunderDelay,20000);
stepTarmacWeather(s,w);assert(!s.thunder,'one-shot output clears');
s=createTarmacWeather();s.flash=32;w.fading=true;stepTarmacWeather(s,w);
assert.equal(s.brightness,128);assert.equal(s.flash,10000);w.fading=false;
const exe=readFileSync('Toy Story 2/toy2.exe'),table=readEffectTable(exe);
const effects=createEffects(table.kinds,table.modes,new RandomStream(new Uint8Array([128])));
const world:EffectWorld={cameraX:0,cameraY:-10000,cameraZ:0,playerX:0,playerY:-10000,playerZ:0,
 playerYaw:0,playerVx:0,playerVz:0,groundAt:()=>0,waterY:null};
const drop=spawnChild(effects,world,100,0,200,0x1b,2);assert(drop);assert(drop.sprite>=0);
for(let i=0;i<1000&&liveEffects(effects).length;i++)stepEffects(effects,world);
assert.equal(liveEffects(effects).length,0,'installed splash expires');
console.log('PASS: rain pool/speed/quota/floors, splash gating and installed lifetime, flash boundary/envelope/cooldown, delayed one-shot thunder and fade suppression.');
